language: python
python:
  - "3.6"
install:
  - "pip install -r requirements.txt"
  - "pip install -r test-requirements.txt"
script:
  - "python setup.py flake8"
  - "python setup.py test"
notifications:
  email: false
